---
- name: Prepare vagrant boxes for OpenShift install
  hosts: nodes
  become: true
#  vars:
#  - okd_repo_rpm: centos-release-openshift-origin311
#  vars_files:
#  - ../secrets/redhat_subscription.yml


  tasks:
  # We don't have dns so lets setup /etc/hosts
  - name: Replace hosts
    action: template src=templates/hosts.j2 dest=/etc/hosts

- name: Add origin repositories
  import_playbook: okd_repositories.pb.yml
  when: openshift_deployment_type == 'origin'

- name: Add enterprise repositories
  import_playbook: osp_repositories.pb.yml
  when: openshift_deployment_type == 'openshift-enterprise'
