---
- name: Prepare vagrant boxes for OpenShift install
  hosts: nodes
  become: true
  vars:
  - release_major: 3
  - release_minor: 11
  vars_files:
  - ../secrets/redhat_subscription.yml


  tasks:
  #
  # Add enterprise repos
  #
  - name: Register nodes with subscription-manager
    redhat_subscription:
      username: "{{ redhat_subscription_username }}"
      password: "{{ redhat_subscription_password }}"
      pool_ids: "{{ redhat_subscription_pools }}"
    register: redhat_subscribe_system

  - name: Disable all RHSM repositories
    rhsm_repository:
      name: '*'
      state: disabled

  - name: Set yum repositories
    rhsm_repository:
      name: "{{ item }}"
    with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
      - rhel-7-fast-datapath-rpms
      - rhel-7-server-ose-{{ release_major }}.{{ release_minor }}-rpms
#    when: redhat_subscribe_system.change
